name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - feature/*
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js (Ensure compatibility with your project dependencies)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      - name: install babel plugin
        run: npm install @babel/plugin-proposal-private-property-in-object --save-dev

      - name: Set environment variables
        run: echo "CI=false" >> $GITHUB_ENV

      # Step 4: Run tests (Ensures that tests pass before build)
      - name: Run tests
        run: npm test

      # Step 5: Build the project
      - name: Build project
        run: npm run build

      # Step 6: Archive build artifacts (e.g., production-ready files in the `build/` directory)
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build/

